#FROM docker.io/calico/cni:v3.27.0
#FROM --platform=linux/arm64 docker.io/calico/cni:v3.27.0
#FROM --platform=linux/arm64 docker.io/calico/node:v3.27.0
#FROM docker.io/calico/node:v3.27.0
#FROM docker.io/calico/kube-controllers:v3.27.0
 #FROM docker.io/trinodb/trino:479
# FROM apache/gravitino:1.1.1
#FROM --platform=linux/arm64 nginx:1.30.0
# --platform=linux/arm64 sonatype/nexus3:3.70.1
#FROM rabbitmq:4.2.9-management
FROM --platform=linux/arm64 postgres:15.19
