#FROM docker.io/calico/cni:v3.27.0
#FROM --platform=linux/arm64 docker.io/calico/cni:v3.27.0
FROM --platform=linux/arm64 docker.io/calico/node:v3.27.0
#FROM docker.io/calico/node:v3.27.0
# FROM docker.io/calico/kube-controllers:v3.27.0
# FROM --platform=linux/arm64 docker.io/calico/kube-controllers:v3.27.0
